### ISSUE TITLE
Sample website is unavailable

### ISSUE THREAD

**Issue by barry-ha** [brggs/Simplicity-for-Lightroom#6]
"Simplicity-for-Lightroom" is a useful example of Lightroom techniques for web development. 

However the demo website at http://www.andrewbriggsphotography.co.uk/simplicity/ reports "this account has been suspended." Would it be possible to bring back a demo somewhere?

**Comment by brggs** [comment]
Thanks for the feedback Barry!

I've checked the demo site into this repo, and it's now being deployed to here: https://simplicity-lightroom-demo.netlify.com/

**Comment by barry-ha** [comment]
Very nice, thank you for bringing back the demo!
